### ISSUE TITLE
CCR Browser link does not work

### ISSUE THREAD

**Issue by CristianoYL** [quinlan-lab/ccr#2]
Hi, thanks for sharing the code and docs. However, I noticed that the link to the CCR browser does not work ([https://rebrand.ly/ccrregions](https://rebrand.ly/ccrregions)). The address is missing `www` in the front. It shall work after changing it to [https://www.rebrand.ly/ccrregions](https://www.rebrand.ly/ccrregions) instead. The same issue happens in the [ccrhtml repo README](https://github.com/quinlan-lab/ccrhtml#ccr-browser) as well.

**Comment by jimhavrilla** [comment]
Can't imagine why that doesn't work.  Clicking on the first link you have there works for me.  As does the one for the HTML.  What are you using to click on the link?

**Comment by CristianoYL** [comment]
It could be the DNS record doesn't get propagated timely. It does work for me now though. I'm closing the issue.

**Comment by jimhavrilla** [comment]
Okay then

**Comment by CristianoYL** [comment]
It seems that this is a reoccuring problem. I can't access the link again.

I tried on both chrome and safari. The internet connection should be alright, I've opened a tab for google without cache. (See attached screenshot)

Adding the `www.` would fix the problem. It looks like a DNS setting issue.

<img width="1127" alt="screen shot 2018-12-13 at 2 11 43 pm" src="https://user-images.githubusercontent.com/17320996/49970756-38de7580-fee1-11e8-97f0-4a790dd8aad6.png">

**Comment by jimhavrilla** [comment]
I can see if adding www fixes your issue but where are you accessing this
from, out of curiosity?

**Comment by CristianoYL** [comment]
I'm accessing it from CA, USA. I'm not sure if it matters.

**Comment by jimhavrilla** [comment]
I was just wondering if it was a country thing or a regional thing. I can
add WWW later tonight and you can tell me if it works for you consistently.
If not, I may have to replace it with the long full link. I'm on a flight
right now so it'll be a bit.

>

**Comment by CristianoYL** [comment]
It's probably something wrong with *rebrand*'s DNS settings. Adding the `www` works for me. Thank you for your time!

**Comment by jimhavrilla** [comment]
I'm sure you are right. I'll add this tonight thanks for letting me know bud

**Comment by jimhavrilla** [comment]
So I added the www prefix to the ccrhtml repo, and it looks like @arq5x added it to this one just moments ago.  So again, thanks for pointing it out

**Comment by CristianoYL** [comment]
Thanks for sharing the site and data. Cheers!
