### ISSUE TITLE
Data format

### ISSUE THREAD

**Issue by CristianoYL** [quinlan-lab/ccr#3]
Hi there, I'm recently processing the CCRs data and I noticed lines like these:

```
1	865645	865660	91.316325156	AL645608.1	865645-865660,865665-865682	VARFALSE,VARFALSE	0.062	0.000	30.580	3.430	11.335235448	47070
1	865665	865682	91.316325156	AL645608.1	865645-865660,865665-865682	VARFALSE,VARFALSE	0.062	0.000	30.580	3.430	11.335235448	47070
```

I'm wondering what is the rationale behind keeping the two ranges separate? The reason I ask is that the **start**, **end** and **ranges** seem to be a bit duplicated. And the **VARFLAG** has to be matched to each range accordingly. If these two ranges need to be separated for scientific reason, can we just omit the **ranges** field and keep the VARFLAG a single value instead of comma-separated entry?

Please let me know. Many thanks!

**Comment by jimhavrilla** [comment]
Hey,

So the starts and ends (columns 2 and 3) will only be duplicated if two different genes overlap the same linear space.  The reason for keeping them separate for multi-exon spanning CCRs like the one you've demonstrated above is that the unique key or (ranges + gene which is also unique always) will allow you to tell if multiple lines are part of the same CCR.  This facilitates the use of tools like BEDTools intersect, though you can also use a BED12 of those regions to accomplish a similar goal.  The main reason I did it though, is the average user would likely misuse it and if the intronic regions of the BED12 blocks intersected a variant or region of interest for them they'd assume it was in the CCR when it is not.

The VARFLAG is just FALSE if it is a true CCR (meaning it doesn't contain a variant) and TRUE if it is a non-constrained region, so if it is a large area with many overlapping INDELs, it could be a multi-exon region of non-constraint.  If your goal is to summarize VARFLAG into one value, that can be done with a pretty simple command; I don't really have any plans to change its representation.  The ranges field can be really helpful so I definitely don't have plans to remove it.

Also, we will probably put out a new release for gnomAD 2.1.1 in the near future.  In addition to helping find unique and multi-exon CCRs, these fields help somewhat with QC and bug checking.

Hopefully this answers your question.

**Comment by CristianoYL** [comment]
Hi @jimhavrilla,

Thanks very much for the detailed explanation. It's all clear to me now.

I'm looking forward to the new release. 

Thanks!

**Comment by jimhavrilla** [comment]
Not a problem. Hopefully the release will be sooner than later
